const workExp = [
  {
    title: 'Software Engineer II',
    start: '2019/1/07',
    end: '2020/06/05',
    company: 'Forcepoint',
    description: [
      'Built front-end using React/Redux and Node.js',
      'Point person with User Accessability to implement Internationalization, I18n',
      'Wrote secure login page that worked with both Okta and AWS Cognito',
      'Made pages that displayed differently depending on user type',
      'Staterd infrastructure that maintained sharable components',
      'Built a proxy to talk to a firewall in Go',
      'Tested in Python DSL Robot',
    ],
  },
  {
    title: 'Junior Software Engineer',
    start: '2017/12/11',
    end: '2018/11/06',
    company: 'Zeeto',
    description: [
      'Built front-end using React/Redux and Node.js',
      'Started separate databases in MongoDB, and AWS S3',
      'Created APIs using AWS API Gateway linked to AWS Lambda',
      'Wrote a test driven environment using Jest',
      'Utilized Azure for URLs containing variables in query params',
      'Made pages that displayed charts from Looker',
      'Carried over publisher over from Legacy platform to new platform',
      'Worked in Drupal which served publisher websites',
      'Added React and Redux to Drupal',
      'Redesigned calendar system for reporting tools',
      'Created a filter system for advertisers to narrow search parameters',
    ],
  },
  {
    title: 'Administrator',
    start: '2016/04/18',
    end: '2017/12/08',
    company: 'Mt. Soledad National Veterans Memorial',
    description: [
      'Project Manager for Website and Mobile App',
      'Coordinate Major holiday events for Memorial day and Veterans Day',
      'Coordinate Veteran Honor Ceremonies with Donors and Trustees',
      'Maintain Database of plaques, membership, and donors.',
    ],
  },
  {
    title: 'CEO and CoFounder',
    start: '2016/01/15',
    end: '',
    company: 'MANDR Development, Inc.',
    description: ['Real estate investment firm'],
  },
  {
    title: 'Board Member',
    start: '2013/10/01',
    end: '2017/04/01',
    company: 'City Heights Town Council',
    description: [
      'A non-profit whose mission is to advocate for and on behalf of our community through building relationships among neighbors and creating safe, attractive neighborhoods to improve the quality of life for its residents.',
    ],
  },
  {
    title: 'Board Member',
    start: '2013/04/01',
    end: '2017/04/02',
    company: 'City Heights Area Planning Committee',
    description: [
      'The San Diego City Council recognizes one official planning group in each community. Groups work with City staff to formulate and implement the General Plan and community plans, and to advise the Planning Commission and City Council on projects.',
    ],
  },
  {
    title: 'Founding Board Member',
    start: '2013/07/01',
    end: '2015/05/01',
    company: 'Exusmed',
    description: [
      'Exusmed planned to redefine healthcare in the rapidly growing and innovative telemedical field – changing how people access healthcare and how providers deliver it. Exusmed delivers cost-effective, higher-quality, proprietary, turnkey solutions to better-bind physicians to their patients, and to give people options for getting the care they need and to accelerate their treatment. Whenever and wherever they need it.',
    ],
  },
  {
    title: 'Campaign Manager/Consultant',
    start: '2011/10/01',
    end: '2014/11/06',
    company: 'Local San Diego Elections',
    description: [
      'Managed fundraising database of over 1500 contacts',
      'Setup daily call list for candidate',
      'Stayed in contact with donors to ensure pledges equal contribution',
      'Planned and setup various fundraising events',
      'Helped raise over $250k for primary election',
      'Headed entire operation of campaign from overall strategy to marketing materials',
      'Created specific goals from analyzing past election cycles & developed tactics to reach them',
      'Built team of dedicated volunteers',
      'Created a network of contacts that ranged from media outlets to community groups to other political organizations',
      'Coordinated forums in a variety of settings & moderators with other Campaign Managers',
      'Created a PPC campaign using social media and search engine advertising tools ',
      'Wrote copy for the campaign and oversaw the total look of campaign website and all graphic content of marketing materials',
    ],
  },
  {
    title: 'Project Coordinator',
    start: '2008/1/1',
    end: '2010/11/01',
    company: 'Bridgepoint Education',
    description: [
      'Implementation of ITSM software to increase department efficiency',
      'Updating help desk systems using the business analyst and engineering departments',
      'Designed a standard operating procedure for the mailroom’s complete operation, and organized roles of the facilities department to find deficiencies',
      'Created the emergency response teams and standard emergencies procedures. Started and implemented a first aid program with a complete overhaul of all first aid kits',
      'Instrumental in opening the company cafeteria including getting the catering staff setup, arranging for grease trap service, and organizing a preventative maintenance schedule for the heating ventilation and air conditioning',
      'Assist in the day to day facility operations of the San Diego facility including acting liaison to outside vendors, coordinating personnel moves, and setup, manage, and tear down of company events',
      'Required excellent time management and organization as well as the ability to be flexible while meeting short deadlines',
    ],
  },
  {
    title: 'Machinist Mate 3rd Class',
    start: '2002/04/17',
    end: '2007/04/16',
    company: 'US Navy',
    description: [
      'As the Work Center Supervisor, oversaw the maintenance scheduling program, including budget analysis for man/hours and predictable overhauls',
      "Conducted the Work Center Training Program and ensured coworker's knowledge of equipment and safety procedures",
      'Acted as the IT department liaison for the engineering department',
      'Worked as a mentor for several coworkers and helped them to achieve promotions',
      'Supervisor of over half of the division on various projects at Submarine Base Groton, Connecticut',
      'In charge of the Hazardous Material and Safety Program for the entire division',
      'Nuclear Reactor Operator Trainee',
    ],
  },
];

export default workExp;
